import { DebugProtocol } from "@vscode/debugprotocol";

export const exceptionBreakpointFilters: DebugProtocol.ExceptionBreakpointsFilter[] = [
  { filter: "0x8", label: "Bus error", default: true },
  { filter: "0xC", label: "Address error", default: true },
  { filter: "0x10", label: "Illegal instruction", default: true },
  { filter: "0x14", label: "Zero divide", default: true },
  // { filter: '0x18', label: 'CHK' },
  // { filter: '0x1C', label: 'TRAPV' },
  { filter: "0x20", label: "Privilege violation", default: true },
];

// What's your vector Victor?
export const vectors = [
  "Reset:SSP",
  "EXECBASE",
  "BUS ERROR",
  "ADR ERROR",
  "ILLEG OPC",
  "DIV BY 0",
  "CHK",
  "TRAPV",
  "PRIVIL VIO",
  "TRACE",
  "LINEA EMU",
  "LINEF EMU",
  null,
  null,
  null,
  "INT Uninit",
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  "INT Unjust",
  "Lvl 1 Int",
  "Lvl 2 Int",
  "Lvl 3 Int",
  "Lvl 4 Int",
  "Lvl 5 Int",
  "Lvl 6 Int",
  "NMI",
  "TRAP 00",
  "TRAP 01",
  "TRAP 02",
  "TRAP 03",
  "TRAP 04",
  "TRAP 05",
  "TRAP 06",
  "TRAP 07",
  "TRAP 08",
  "TRAP 09",
  "TRAP 10",
  "TRAP 11",
  "TRAP 12",
  "TRAP 13",
  "TRAP 14",
  "TRAP 15",
];