import { DebugProtocol } from "@vscode/debugprotocol";

export const exceptionBreakpointFilters: DebugProtocol.ExceptionBreakpointsFilter[] =
  [
    { filter: "0x8", label: "Bus error", default: true },
    { filter: "0xC", label: "Address error", default: true },
    { filter: "0x10", label: "Illegal instruction", default: true },
    { filter: "0x14", label: "Zero divide", default: true },
    // { filter: '0x18', label: 'CHK' },
    // { filter: '0x1C', label: 'TRAPV' },
    { filter: "0x20", label: "Privilege violation", default: true },
  ];

// What's your vector Victor?
export const vectors = [
  "RESET_SSP",
  "RESET_PC",
  "BUS_ERROR",
  "ADR_ERROR",
  "ILLEG_OPC",
  "DIV_BY_0",
  "CHK",
  "TRAPV",
  "PRIVIL_VIO",
  "TRACE",
  "LINEA_EMU",
  "LINEF_EMU",
  null,
  null,
  null,
  "INT_UNINIT",
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  "INT_UNJUST",
  "L1",
  "L2",
  "L3",
  "L4",
  "L5",
  "L6",
  "NMI",
  "TRAP_00",
  "TRAP_01",
  "TRAP_02",
  "TRAP_03",
  "TRAP_04",
  "TRAP_05",
  "TRAP_06",
  "TRAP_07",
  "TRAP_08",
  "TRAP_09",
  "TRAP_10",
  "TRAP_11",
  "TRAP_12",
  "TRAP_13",
  "TRAP_14",
  "TRAP_15",
];